[build]
  publish = "static_site/"
  command = "echo 'No build command needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = []}
