[build]
  publish = "static_site/"
  command = "echo 'No build command needed for static site'"

[build.environment]
  NODE_VERSION = "18"
  PHP_VERSION = "8.1"

# WordPress-specific headers
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"

# Handle WordPress permalinks
[[redirects]]
  from = "/*"
  to = "/index.php/:splat"
  status = 200
  force = false
  conditions = {Path = {glob = "!/*.php"}, Path = {glob = "!/*.js"}, Path = {glob = "!/*.css"}, Path = {glob = "!/*.svg"}, Path = {glob = "!/*.jpg"}, Path = {glob = "!/*.jpeg"}, Path = {glob = "!/*.png"}, Path = {glob = "!/*.gif"}}

# Fallback redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
